"""add image_blob_keys column to posts table

Revision ID: ab17e43a40e0
Revises: 02b0f0c66b61
Create Date: 2025-08-18 15:39:03.105352+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab17e43a40e0'
down_revision: Union[str, None] = '02b0f0c66b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_blob_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Azure Blob Storage 키 배열',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_blob_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Azure Blob Storage 키 배열',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###
