"""Add coordinate and region fields to recipients

Revision ID: 02b0f0c66b61
Revises: 
Create Date: 2025-08-17 14:55:57.413573+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02b0f0c66b61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_groups', 'deadline_type',
               existing_type=postgresql.ENUM('SECOND_SUNDAY', 'FOURTH_SUNDAY', name='deadlinetype'),
               type_=sa.Enum('SECOND_SUNDAY', 'FOURTH_SUNDAY', name='deadlinetype', native_enum=False),
               existing_comment='마감일 타입',
               existing_nullable=False)
    op.alter_column('family_groups', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='groupstatus'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='groupstatus', native_enum=False),
               existing_comment='그룹 상태',
               existing_nullable=False)
    op.add_column('recipients', sa.Column('road_address', sa.String(length=500), nullable=True, comment='도로명주소'))
    op.add_column('recipients', sa.Column('jibun_address', sa.String(length=500), nullable=True, comment='지번주소'))
    op.add_column('recipients', sa.Column('address_type', sa.String(length=10), nullable=True, comment='주소타입(ROAD/JIBUN)'))
    op.add_column('recipients', sa.Column('latitude', sa.Float(), nullable=True, comment='위도'))
    op.add_column('recipients', sa.Column('longitude', sa.Float(), nullable=True, comment='경도'))
    op.add_column('recipients', sa.Column('region_1depth', sa.String(length=50), nullable=True, comment='시/도'))
    op.add_column('recipients', sa.Column('region_2depth', sa.String(length=50), nullable=True, comment='구/군'))
    op.add_column('recipients', sa.Column('region_3depth', sa.String(length=50), nullable=True, comment='동/면'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipients', 'region_3depth')
    op.drop_column('recipients', 'region_2depth')
    op.drop_column('recipients', 'region_1depth')
    op.drop_column('recipients', 'longitude')
    op.drop_column('recipients', 'latitude')
    op.drop_column('recipients', 'address_type')
    op.drop_column('recipients', 'jibun_address')
    op.drop_column('recipients', 'road_address')
    op.alter_column('family_groups', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='groupstatus', native_enum=False),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='groupstatus'),
               existing_comment='그룹 상태',
               existing_nullable=False)
    op.alter_column('family_groups', 'deadline_type',
               existing_type=sa.Enum('SECOND_SUNDAY', 'FOURTH_SUNDAY', name='deadlinetype', native_enum=False),
               type_=postgresql.ENUM('SECOND_SUNDAY', 'FOURTH_SUNDAY', name='deadlinetype'),
               existing_comment='마감일 타입',
               existing_nullable=False)
    # ### end Alembic commands ###
